{"name": "test_login_fail[test_info1]", "status": "passed", "attachments": [{"name": "stdout", "source": "a559bbab-dbe9-41a7-a4df-c88f51322b12-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'mobile': '13502811019', 'pwd': '123456', 'expected': '手机号码或密码错误！请联系管理人员。'}"}], "start": 1611567178458, "stop": 1611567182472, "uuid": "d292ec09-ffd8-41c2-8b63-be38224c7de7", "historyId": "a2e1e6ff4a78458533bb1da47a2a7f22", "testCaseId": "912ae1978968c73f58f65a524468c60c", "fullName": "cases.login_test.TestLogin#test_login_fail", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "staging"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20170703AYCC"}, {"name": "thread", "value": "17024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.login_test"}]}